version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - database
    volumes:
      - ./backend:/var/www/html/backend

  frontend:
    image: node:14
    command: "npm run serve"
    ports:
      - 8080:8080
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - VUE_APP_API_URL=http://backend:8000/api

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
